dimensiones con numpy

In [1]:
import numpy as np


In [9]:
scalar = np.array(42, dtype = 'float64')
print(scalar)
scalar.ndim
r=scalar.astype('int64')
r.dtype

42.0


dtype('int64')

In [10]:
vector = np.array([1,3,6,2,8])
print(vector)
vector.ndim

[1 3 6 2 8]


1

In [16]:
matriz = np.array([[1,3,6,2,8],[2,6,7,8,9],[1,6,7,4,9]])
print(matriz)
matriz.ndim

[[1 3 6 2 8]
 [2 6 7 8 9]
 [1 6 7 4 9]]


2

In [30]:
tensor = np.array([[[1,3,6,2,8],[2,6,7,8,9],[1,6,7,4,9]],[[1,3,6,2,8],[2,6,7,8,9],[1,6,7,4,9]]])
print(tensor[1][2][1])
tensor.ndim

6


3

In [33]:
#redimensionamiento de los arrays
vector10 = np.array([1,3,6,2,8], ndmin=10)
print(vector10)
vector10.ndim


[[[[[[[[[[1 3 6 2 8]]]]]]]]]]


10

In [56]:
#expandir una dimension en las filas con axis=1 si quisiera columnas seria axis=0
expandY = np.expand_dims(np.array([1,3,6,2,8]), axis=0)
expandYY =  np.expand_dims(expandY, axis=0)
expandX = np.expand_dims(np.array([1,3,6,2,8]), axis=1)
expandXX = np.expand_dims(expandX, axis=1)
print(expandX[1][0])
print(expandY[0][1])
print(expandXX[3][0][0])
print(expandYY[0][0][1])

3
3
2
3


In [57]:
#borrar dimensiones
vector1 = np.squeeze(vector10)
print(vector1)
vector1.ndim

[1 3 6 2 8]


1

como crear arrays con numpy con metodos de la libreria


In [58]:
#me crea un array en el rango de los nuemro que le de sin tomar el ultimo 
#se le puede agregar el step
np.arange(0,10,3)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
#me crea un array de zeros en float
np.zeros((10,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [62]:
#me crea un array de unos 
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [5]:
#crear un array(matriz) en un rango de numeros y cuantos datos quiero en este rango
#ejemplo quiero datos del 0 - 10 y que hayan 100 datos entre este rango 
Examplea=np.linspace(0,10,100)
print(Examplea)
print(Examplea.ndim)

[ 0.          0.1010101   0.2020202   0.3030303   0.4040404   0.50505051
  0.60606061  0.70707071  0.80808081  0.90909091  1.01010101  1.11111111
  1.21212121  1.31313131  1.41414141  1.51515152  1.61616162  1.71717172
  1.81818182  1.91919192  2.02020202  2.12121212  2.22222222  2.32323232
  2.42424242  2.52525253  2.62626263  2.72727273  2.82828283  2.92929293
  3.03030303  3.13131313  3.23232323  3.33333333  3.43434343  3.53535354
  3.63636364  3.73737374  3.83838384  3.93939394  4.04040404  4.14141414
  4.24242424  4.34343434  4.44444444  4.54545455  4.64646465  4.74747475
  4.84848485  4.94949495  5.05050505  5.15151515  5.25252525  5.35353535
  5.45454545  5.55555556  5.65656566  5.75757576  5.85858586  5.95959596
  6.06060606  6.16161616  6.26262626  6.36363636  6.46464646  6.56565657
  6.66666667  6.76767677  6.86868687  6.96969697  7.07070707  7.17171717
  7.27272727  7.37373737  7.47474747  7.57575758  7.67676768  7.77777778
  7.87878788  7.97979798  8.08080808  8.18181818  8

In [6]:
#me crea una matriz con la diagonal en 1 y el resto en zero
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [8]:
#crear un array(matriz) de numeros aleatorios entre el 0 y el 1
print(np.random.rand()) #<--- un sulo numero
print(np.random.rand(4)) #<--- array con cuatro numeros
print(np.random.rand(4,2))#<--- matriz de forma 4x2

0.04855719783311896
[0.73545848 0.88215825 0.998662   0.20619338]
[[0.69595491 0.67132326]
 [0.13432328 0.90904447]
 [0.57566772 0.30682254]
 [0.43591999 0.43032945]]


In [9]:
#para crear un array con numeros enteros en un rango establecido por nosotros
print(np.random.randint(1,50)) #<-- crea un solo numero
print(np.random.randint(1,30,(10,2))) #<--- crea una matriz con numeros enteros al azar con la forma 10x2

37
[[ 1  5]
 [29 19]
 [23 14]
 [20  3]
 [16 25]
 [29  8]
 [ 4 28]
 [ 9 24]
 [ 6  1]
 [ 5 17]]


veremos las formas de las matrices y los metdos shape y reshape

In [3]:
arra = np.random.randint(1,6,(2,3))
#shape me devuelve la forma de la matriz 
print(arra.shape)
#reshape me cambia la forma de la matriz en cuanto se mantanga en las mismas dimensiones (no puede crear ni borrar datos)
print(arra.reshape(3,2))

(2, 3)
[[5 3]
 [5 5]
 [5 4]]


Funciones(metodos) mas usados en numpy 

In [7]:
ar=np.random.randint(1,20,10)
matriz = ar.reshape(2,5)
print(matriz)


[[ 8  6  8 19 17]
 [ 9  2 12 17 16]]


In [9]:
#Obtener el numero mayor de una matriz
matriz.max()
#si queremos obtener el numero mayor por ejes agregamos en la funcion un 0 --> columnas y un 1 --> Filas
matriz.max(0)

array([ 9,  6, 12, 19, 17])

In [11]:
#obtener el indice de donde se encuentra el numero mayor (me devuelve el indice del primer numero mayor si se repite)
matriz.argmax()
#tambien me entrega los indices por ejes
matriz.argmax(1)

array([3, 3], dtype=int64)

In [13]:
#obtener el numero menor de una matriz
matriz.min()
#tiene las mismas propiedades que la funcion max con los ejes
matriz.min(1)

array([6, 2])

In [14]:
#obtener el indice del numero menor de una matriz(funciona igual que el argmax)
matriz.argmin()

6

In [15]:
#obtener la diferencia entre el pico mas alto al pico mas bajo(del mayor al menor)
print(ar.ptp()) #numero mayor 19 y menor 2 19-2 = 17
print(matriz.ptp(0)) #tiene la misma pripiedad de los ejes

17
[1 4 4 2 1]


In [26]:
#obtener el percentil de un array o matriz
np.percentile(matriz,50)

10.5

In [30]:
#organizar de menor a mayor el array o matriz
ar.sort()
matriz.sort()
matriz



array([[ 2,  6,  8,  8,  9],
       [12, 16, 17, 17, 19]])

In [34]:
#Obtener la mediana de un array o matriz
np.median(ar)
np.median(matriz,0) # tambien tiene la propiedad de los ejes

array([ 7. , 11. , 12.5, 12.5, 14. ])

In [35]:
#Obtener la variacion estandar 
print(np.std(ar))
print(np.std(matriz))


5.370288632839022
5.370288632839022


In [36]:
#obtener la varianza 
print(np.var(ar))
print(np.var(matriz))

28.840000000000003
28.840000000000003


In [37]:
#obtener la media de un array o matriz
print(np.mean(ar))
print(np.mean(matriz))

11.4
11.4


In [69]:
#concatenar dos array, deben tener la misma dimension 
a = np.array([[1,2],[3,4]])
b = np.array([4,6])
print(b.shape)
print(a.shape)
np.concatenate((a,b), axis=0)

(2,)
(2, 2)


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [70]:
#organizamos el error
b = np.expand_dims(b,axis=0)
print(b.shape)



(1, 2)


In [73]:

print(np.concatenate((a,b),axis=0))
#si queremos concatenar por sus filas hacemos la transpuesta de B
print(np.concatenate((a,b.T),axis=1))

[[1 2]
 [3 4]
 [4 6]]
[[1 2 4]
 [3 4 6]]


vamos a ver el copy
se puede generar varios errores al uno usarlo ya que al modificar la copia se puede modificar el original


In [77]:
Z = np.arange(0,10)
Trozo_Z=Z[0:6]

In [80]:
Trozo_Z[:] = 0
print(Trozo_Z)
#cambiamos los valores de trozo de Z que es una copia de los primeros 5 valores de Z pero tambien me cambio Z
print(Z)

[0 0 0 0 0 0]
[0 0 0 0 0 0 6 7 8 9]


In [84]:
#como hacerlo correctamente
Z_Copy = Z.copy()
Z_Copy[:]=100
print(Z_Copy)
print(Z)



[100 100 100 100 100 100 100 100 100 100]
[0 0 0 0 0 0 6 7 8 9]


condiciones (como SQL con where)

In [95]:
C = np.linspace(1,10,10, dtype = 'int8')

In [96]:
#obtener valores segun condiciones
C[(C>5) & (C<9)]
C[C>5] = 99
c=C
print(c)


[ 1  2  3  4  5 99 99 99 99 99]


Operaciones 

In [97]:
#en este caso me multiplica dos veces los valores ya existentes
lista = [1,2]
lista * 2

[1, 2, 1, 2]

In [98]:
#haciendolo con numpy
Arr = np.arange(0,10)
Arr2 = Arr.copy()


In [99]:
Arr2 * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [100]:
1 / Arr

C:\Users\carlo\AppData\Local\Temp\ipykernel_18892\1313145314.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / Arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])